# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d681792855cb09f90325322288e0e706f639fe8231c0739a6d9708dd4135ef6b460c50d6ccdebd0a539de5a3d8229f6161f5409664bd0ddae1c518ea2d4201ad

test:
  secret_key_base: a46edcff9a3d522fdb1618052d383865eaa3a9f34e02a26dfd3a1df9c93ccb5285f9b304e1809bae68210c30797e19cf7c6430c1e7090c1d681e1af3567b1857

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
